//
//  MockData.swift
//  TTAi
//
//  Created by Tuệ Tuệ AI on 2026-03-21.
//

import Foundation

// MARK: - Mock Data for Testing and Development

struct MockData {
    
    // MARK: - Sample Chat Messages
    
    static let sampleChatMessages: [ChatMessage] = [
        ChatMessage(
            role: .assistant,
            content: "Hi! I'm Tuệ Tuệ AI. I can help you with programming, learning, and answering questions. Which model would you like to use today?",
            model: .gptMini
        ),
        ChatMessage(
            role: .user,
            content: "How do I make a network request in Swift?",
            model: .gptMini
        ),
        ChatMessage(
            role: .assistant,
            content: "In Swift, you can use URLSession. Here's an example with async/await:\n\n```swift\nfunc fetchData(from url: URL) async throws -> Data {\n    let (data, _) = try await URLSession.shared.data(from: url)\n    return data\n}\n```\n\nThis uses Swift Concurrency for clean, readable code.",
            model: .gptMini
        ),
        ChatMessage(
            role: .user,
            content: "Can you explain the difference between GPT and Gemini?",
            model: .geminiPro
        ),
        ChatMessage(
            role: .assistant,
            content: "GPT (OpenAI) excels at reasoning and long-context tasks, while Gemini (Google) is strong at multimodal understanding and up-to-date information. DeepSeek offers cost-effective performance for debugging and research.",
            model: .geminiPro
        ),
        ChatMessage(
            role: .user,
            content: "I'm getting a 'nil' error in my Swift code",
            model: .deepSeekChat
        ),
        ChatMessage(
            role: .assistant,
            content: "The 'nil' error usually means you're trying to use an optional value without unwrapping it. Use `if let`, `guard let`, or the nil-coalescing operator `??`. Example:\n\n```swift\nif let unwrappedValue = optionalValue {\n    // Use unwrappedValue safely\n}\n```",
            model: .deepSeekChat
        )
    ]
    
    // MARK: - Sample Code Snippets
    
    struct CodeSnippet {
        let language: String
        let title: String
        let code: String
        let description: String
    }
    
    static let sampleCodeSnippets: [CodeSnippet] = [
        CodeSnippet(
            language: "Swift",
            title: "Network Request",
            code: """
            import Foundation
            
            class NetworkService {
                func fetchUserData() async throws -> User {
                    let url = URL(string: "https://api.example.com/user")!
                    let (data, _) = try await URLSession.shared.data(from: url)
                    return try JSONDecoder().decode(User.self, from: data)
                }
            }
            """,
            description: "Async/await network request with error handling"
        ),
        CodeSnippet(
            language: "Python",
            title: "Data Analysis",
            code: """
            import pandas as pd
            import numpy as np
            
            def analyze_data(filepath):
                df = pd.read_csv(filepath)
                summary = {
                    'mean': df.mean(),
                    'median': df.median(),
                    'std': df.std()
                }
                return summary
            """,
            description: "Basic data analysis with pandas"
        ),
        CodeSnippet(
            language: "JavaScript",
            title: "React Component",
            code: """
            import React, { useState } from 'react';
            
            function Counter() {
                const [count, setCount] = useState(0);
                
                return (
                    <div>
                        <p>Count: {count}</p>
                        <button onClick={() => setCount(count + 1)}>
                            Increment
                        </button>
                    </div>
                );
            }
            """,
            description: "Simple React counter component with hooks"
        )
    ]
    
    // MARK: - Sample API Responses
    
    static let mockAPIResponse = """
    {
      "id": "chatcmpl-123",
      "object": "chat.completion",
      "created": 1677652288,
      "model": "cliproxy/gpt-mini",
      "choices": [
        {
          "index": 0,
          "message": {
            "role": "assistant",
            "content": "This is a mock response from the AI assistant. In a real scenario, this would be generated by the selected model."
          },
          "finish_reason": "stop"
        }
      ],
      "usage": {
        "prompt_tokens": 10,
        "completion_tokens": 20,
        "total_tokens": 30
      }
    }
    """
    
    // MARK: - Sample Error Responses
    
    static let networkErrorResponse = """
    {
      "error": {
        "message": "Network connection lost",
        "type": "network_error",
        "code": 503
      }
    }
    """
    
    static let rateLimitErrorResponse = """
    {
      "error": {
        "message": "Rate limit exceeded. Please try again later.",
        "type": "rate_limit_error",
        "code": 429
      }
    }
    """
    
    // MARK: - Helper Methods
    
    static func generateMockResponse(for prompt: String, model: AIModel) -> String {
        let responses = [
            "I understand you're asking about \(prompt). Let me help you with that.",
            "Based on your question about \(prompt), here's what I can tell you...",
            "That's an interesting question about \(prompt). Here's my analysis:",
            "Regarding \(prompt), the key points are:",
            "I've analyzed your query about \(prompt). Here are the results:"
        ]
        
        let randomResponse = responses.randomElement() ?? "I'm here to help with \(prompt)."
        return "\(randomResponse) [Mock response from \(model.displayName)]"
    }
    
    static func generateMockCode(for language: String, description: String) -> String {
        switch language.lowercased() {
        case "swift":
            return """
            // Generated Swift code for: \(description)
            import Foundation
            
            struct Solution {
                static func execute() {
                    print("Hello from Swift!")
                    // Your implementation here
                }
            }
            
            Solution.execute()
            """
        case "python":
            return """
            # Generated Python code for: \(description)
            def main():
                print("Hello from Python!")
                # Your implementation here
            
            if __name__ == "__main__":
                main()
            """
        case "javascript":
            return """
            // Generated JavaScript code for: \(description)
            function main() {
                console.log("Hello from JavaScript!");
                // Your implementation here
            }
            
            main();
            """
        default:
            return "// Code generation for \(language): \(description)"
        }
    }
}

// MARK: - Mock API Client for Testing

class MockAPIClient {
    static let shared = MockAPIClient()
    
    private init() {}
    
    func sendChatMessage(
        messages: [ChatMessage],
        model: AIModel,
        temperature: Double = 0.7
    ) async throws -> String {
        // Simulate network delay
        try await Task.sleep(nanoseconds: 1_000_000_000) // 1 second
        
        let lastMessage = messages.last?.content ?? "Hello"
        return MockData.generateMockResponse(for: lastMessage, model: model)
    }
    
    func generateCode(
        description: String,
        language: String
    ) async throws -> String {
        // Simulate network delay
        try await Task.sleep(nanoseconds: 800_000_000) // 0.8 seconds
        
        return MockData.generateMockCode(for: language, description: description)
    }
}

// MARK: - Development Flag

#if DEBUG
let useMockData = true
#else
let useMockData = false
#endif